### ISSUE TITLE
Migrate backend functionality

### ISSUE THREAD

**Issue by dongheenam** [dongheenam/test-builder#2]
## Tasks

- [ ] Decide on the mode of communication between front and back (REST API or form actions)
- [ ] Write the CRUD functionality
- [ ] Migrate the existing Prisma code
