### ISSUE TITLE
Migrate core frontend logic

### ISSUE THREAD

**Issue by dongheenam** [dongheenam/test-builder#3]
Most of the frontend logic has already been moved to Svelte, but there are just a few that still needs to be done.

## Tasks
- [ ] drag to shuffle within the bucket
- [ ] move questions from list to bucket
- [ ] send UPDATE request on save in the editor
